"""add fields ml, rule and final score to url_checks

Revision ID: f8287b390001
Revises: 1cd4eb2e4dd0
Create Date: 2026-07-06 23:47:52.460673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8287b390001'
down_revision: Union[str, Sequence[str], None] = '1cd4eb2e4dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_checks', sa.Column('rule_score', sa.Float(), nullable=True))
    op.add_column('url_checks', sa.Column('ml_score', sa.Float(), nullable=True))
    op.add_column('url_checks', sa.Column('final_score', sa.Float(), nullable=True))
    op.drop_column('url_checks', 'risk_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_checks', sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('url_checks', 'final_score')
    op.drop_column('url_checks', 'ml_score')
    op.drop_column('url_checks', 'rule_score')
    # ### end Alembic commands ###
